[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
bip39 = "2.2.2"
mutex = "1.0.2"
rand = "0.8"
sha2 = "0.10.9"
solana-sdk = "4.0.0"
tokio = { version = "1.49.0", features = ["full"] }
